version: '2'

services:
  nifi:
    image: apache/nifi
    privileged: true
    ports:
      - "9090:9090"
    volumes:
    - "./data:/opt/nifi/nifi-1.6.0/data"
    - "./conf:/opt/nifi/nifi-1.6.0/conf"
    - "./logs:/opt/nifi/nifi-1.6.0/logs"
    - "./content_repository:/opt/nifi/nifi-1.6.0/content_repository"
    - "./database_repository:/opt/nifi/nifi-1.6.0/database_repository"
    - "./flowfile_repository:/opt/nifi/nifi-1.6.0/flowfile_repository"
    - "./provenance_repository:/opt/nifi/nifi-1.6.0/provenance_repository"
    environment:
      IS_CLUSTER_NODE: 1
      ZK_NODES_LIST: 172.16.5.90
      ELECTION_TIME: 1 min
      NIFI_WEB_HTTP_PORT: 9090

